- components/AppBar.js
Used flexbox in app bar which is more reliable
Bonus Refactored svg to SvgIcon
closes #16 
closes #17
> Refactored AppBar using flexbox

- .babelrc
- .eslintignore
- __tests__/appbar.test.js
- __tests__/index.test.js
- __tests__/layout.test.js
- components/Drawer.js
- package.json
- shim.js
- yarn.lock
closes #7 
Added unit testing using jest and enzyme.
End to end testing in a later PR.
> Unit testing

- CONTRIBUTING.md
- README.md
- pages/faculty.js
Added instructions on how to keep your fork up-to-date to the [CONTRIBUTING.md](CONTRIBUTING.md) file.
Made the reference to CONTRIBUTING clickable in [README.md](README.md)
> add instructions to keep up-to-date to CONTRIBUTING.md

- .gitignore
- README.md
- __tests__/appbar.test.js
- components/AppBar.js
Started This following issue [#29](https://github.com/fus-marcom/franciscan-react/issues/29) started by @MrNime
This adds a NextJs `Link` component as suggested by @SebastianCApostolescu in the issue, to the `AppBar`, I also added the test for it. I also changed the links that were pointing to @JesseRWeigel 's last project in `README.md` so they point to this project instead. 
This is my first ever open source PR, and my first ever front end contribution to a real project as well, so any feed back is appreciated, I hope I did everything correct :) Thanks
> Homepage url on logo

- components/Drawer.js
all good so far adding the link to the logo on the drawer.
> add link to home on the logo inside the drawer close #29

- e2e/tests/faculty.spec.js
- lib/initApollo.js
- pages/faculty.js
- server.js
Jesse I resolved the caching issue
see https://github.com/fus-marcom/franciscan-react/blob/313ee0d902dda87401bcd57ac8b1342c0bd7b6b0/server.js#L13 you have setted the LRU cache for 1 hr even  in dev mode which will cache the rendered page. I have fixed that.
Also I have written 2 test for faculty page and added domain for wp site.
Make sure you restart your server
> Add domain, test for faculty page and fix cache issue

- package.json
- yarn.lock
> update material-ui to last version

- components/AppBar.js
closes #56 
Some good practice with  making changes in the same file as the previous PR, without including those changes in this one.
> changes donate button to Access FUS link

- components/Drawer.js
resolves #55 
* Moved divider inside the list of drawer-items.
* Added links to these external sites underneath it.
* Added Icon to signal to users that they are leaving the site they are on.
(open them in a new tab)
* Remove the underline and the red color on link click.
If you'd like, I can break those links out into their own component to avoid clutter in the file.
> add links in drawer

- lib/fusTheme.js
- pages/index.js
Make sure #67 is merged before merging this
While committing last PR our tests caught some errors caused by breaking changes in MUI
Which caused this color issue
Now it is fixed. :+1:
> fix(index.js): Fix the breaking changes in MUI beta 30-31

- pages/test-gql.js
- server.js
Some thing like request for service-worker and favicon was giving 500 error. It is now fixed
> fix: Fix some 500 error request on the server

- components/AppBar.js
- components/Drawer.js
- components/DrawerItem.js
- components/InvertedButton.js
- components/ProfileCard.js
- data/drawerMenu.js
- pages/index.js
- server.js
As you have setup custom next js server the client side routing doesnt work the usual way. You can see by running the current code that browser **reloads** the page when you click a link in Drawer which should **not** be the case. For that to work next Link component needs the url passed to the server  in the href prop(means the `/pages?id=something&type=something`) and for the representation link (means `/about/mission`) needs to pass in the as prop. I have added an asUrl key to each link item. You need to fill them will server query string links. I have filled one or two. You can refer the server.js file and see what you need to pass. It was a ton of non code related work that I cant do(SORRY for that). You may take help from your student workers for this :wink: . See …
> Fix for client side routing and error warnings

- components/DrawerItem.js
> Make entire li clickable links in side drawer for all menu items

- components/Drawer.js
> Add 'cursor: pointer' style to logo in drawer

- components/AppBar.js
- components/AppBarMenuItem.js
- components/Drawer.js
- components/DrawerItem.js
- components/Footer.js
- components/Hero.js
- components/ListCard.js
- components/ProfileCard.js
- components/TextSection.js
- pages/minor.js
- pages/news.js
Hello,
I moved some of this around for you as I thought I would help out. Something is up with your pre-commit hook as you're linting with standard and single quotes but it's not working. 
I noticed that you're calling a loading screen but you can wrap that into a Higher Order Component so you don't need to duplicate it.
> Refactoring

- pages/search.js
Slight changed sorting logic and added dropdown to choose sorting direction.
Needs extra CSS.
> fix(search.js): make sort work and add dropdown

- __tests__/__snapshots__/index.test.js.snap
- __tests__/__snapshots__/textsection.test.js.snap
- __tests__/index.test.js
- __tests__/textsection.test.js
- components/InvertedButton.js
- jest.config.json
- package.json
- shim.js
automatically run enzyme-to-json via serializer
used  `mount` for the wrapper of the `TextSection` component since it is wrapped with a `withStyles`
used `render` for the wrapper of the `index` page, leading to a warning, probably originating from MUI.
See TravisCI to see the error
edit: fixed in commit. Did travis timeout or something, it should have passed.
> test: set up json serializer for enzyme

- pages/faculty.js
Online test: https://regex101.com/r/dAmDZ8/1/
> use regex to change CVLink text to View CV

- components/AppBar.js
When running the website, I noticed that the search SVG icon and the search bar input were very far apart and I decided to see what it would like with them closer together. In my opinion, I believe it looks better.
> Move search svg down 2px and input up 6px to line them up better.

- package.json
> fix(package): update next to version 6.1.1

- components/Layout.js
Add download links for Chrome and Firefox. Picked en-US version for Firefox.
> Add download links for Chrome and Firefox
