fus-marcom/franciscan-react

- components/Footer.js
- components/Layout.js
- pages/faculty.js
includes #27 
Footer now sticks to the bottom, even is the page content is not big enough to fill the entire viewport.
I changed 1 style property in the Footer.js file.
The flexGrow propery caused the footer to expand with empty space.
This feature wasn't asked for, and I don't even know if I did it right, so I expect nothing, only more pull-request exercise.
> Sticky footer

- pages/faculty.js
Removed the unused `export` keyword in the faculty.js file.
Very minor change, but happy I could train that forking/branching/pullrequesting muscle.
edit: Question, if I wanted to make additional changes (making the footer sticky using flexbox), how would I go about that? Another PR that doesn't include this change, a PR that builds on this branch but is unrelated?
edit2: Did what I thought the `contributing.md` file wanted me to do.
> remove unused named export keyword

- lib/initApollo.js
- lib/queries/posts.js
- lib/withData.js
- package.json
- pages/test-gql.js
- yarn.lock
Remember to `yarn`.
There is an example in `pages/test-gql.js`
Test endpoint: http://localhost:3000/test-graphql
1. There is a `withData` HOC which you wanna import in root page where you want to use graphql as it does the ssr.
2. Change the URL in initApollo.js
> Add graphql using Apollo 2.0

- e2e/tests/faculty.spec.js
- pages/faculty.js
The issue was that there is bug in js which didnt matched replace in linebreaks.
I have used regexp now.
Now it is also tested in e2e tests
> Fix details tag replacement

- components/Drawer.js
- yarn.lock
I remove the class string drawerImg and create as a property on the object styles and as value I set the css rule margin: 0 auto so the logo can be centered closes #47
> fix: center logo on side bar

- components/AppBar.js
closes #50 
Centered social icons using flexbox.
Made them bigger (the height value is at 32px now, feel free to change it)
Note to everyone submitting a PR: make sure yarn run dev is running at the moment you commit or the commit will fail.
> make social icons larger and center them [closes #50]

- components/Drawer.js
resolves #46 
The color of the search text that pops out on focus is controlled by
```
inputLabelFocused: {
color: '#998643'
},
```
The color or the underline when focussed in controlled by
```
inputInkbar: {
'&:after': {
backgroundColor: '#998643'
}
}
```
suggestion: put the color that is used inside the Mui-theme and pull it out from there.
> change color of search label and inkbar on focus

- components/Footer.js
- package.json
- yarn.lock
Added [commitizen](https://github.com/commitizen/cz-cli) support to this repo.
Follows the [conventional changelog](https://github.com/conventional-changelog/conventional-changelog) rules.
Check it out, see if it's something desirable. 
Possible option for #61 
To use: 
1. `yarn` to install needed dependencies
1. Make your changes
1. Git add like you normally would but instead of `git commit`, use `yarn run cm`
(I couldn't name it commit because the precommit hooks would run twice then, so I chose cm)
If a commit fails (because it fails the tests) you can fix the tests and then run `yarn run cm --retry`,
this will retry the commit with the same info you filled in before (commit message etc)
sorry for the test commits on this branch, testing this required me to actually commit a few times. …
> add Commitizen support

- components/AppBar.js
resolves #48 
Struggling on mobile part because of the lack of media queries in CSSinJS
Problems here as well. I wanted to set focus using a ref and then calling `.focus()` on it. No-go, you can't use refs on functional components, which Mui's TextField is.
Same issue here: https://github.com/mui-org/material-ui/issues/8061 but sadly this issue got closed without response.
Conditionally rendering the TextField and adding the `autoFocus` prop loses the animation.
* Fixed by changing `TextField` to `Input` and calling `inputRef`, not just `ref` (that gets you the `withStyles` component, not the actual input-html-tag)
Should this also:
* Pull out the searchtext/boolean/onChange handler to higher component in the chain
* Share the searchText between the two inputs
* Reset searchText state to …
> add search toggle

- .babelrc
- package.json
- pages/page.js
- yarn.lock
closes #65 
Phewww. Finally I got this to work.
There is a issue going on in exports of react apollo 2.1 so to get this to work I need to add a little babel plugin 
https://github.com/apollographql/react-apollo/issues/1591#issuecomment-361864293
Screenshot 
PS: *FIRST TIME IN LIFE GOT BENIFIT OF WRITING TEST*
there is a breaking change in MUI beta 31 regarding buttons. Our test caught that while I was commiting :smile: 
Which caused this....
~Will be fixing this in next PR~ Fixed the issue in PR #69 :+1:
> feat(page,.babelrc): Properly configure apollo client 2.1 react using babel

- package.json
- yarn.lock
As @pantharshit00 suggested, used nodemon to automatically restart the server on changes to `server.js`
Had to add the `--watch` flag and watch for changes in `server.js` specifically or the server would have a little meltdown and refuse to work.
In my testing prior to adding this I also noticed some routes don't work, like `/accounting` or `/economics`
edit: some autoformatting changes made it in again, only meaningful change is adding `nodemon `to `devDependencies `and the changing of the `dev `script in `package.json`
> build(package.json): add nodemon to auto refresh on server.js changes

- package.json
- server.js
- yarn.lock
fix #71, fix #72 
This prevents the errors in the console from accumulating and enables HMR again while keeping the universal route functional.
This also extends to universal route to catch all current (and hopefully future) routes, using a translation object.
> fix(server.js): prevent errors from _next/ route and extend universal route

- pages/major.js
For issue #85 
The problem is caused by lines 47-49 in static/styles/news.css:
```
listviewimage, detailstype, rightcolumnblogs, br {
display: none;
}
```
It includes the `br` selector, so `<br>` tags are ineffective.
I didn't want to break anything by removing the `br` selector, so I just created a style to unset it in major.js
> Unset styling that hides br tags in major.js

- .vscode/launch.json
- pages/hat.js
- pages/hatList.js
- server-old.js
- server.js
Changed the way the routing works.
and tell me what doesn't work.
The code still uses a bunch of guarding `if`-statements for the moment but the logic should be easier to follow.
It fills all the variables that are used by `renderAndCache` with the right information.
At the end of the logic tree, it uses those values and actually calls `renderAndCache` with them
On page key expansion:
Now you can use a different page (a file in the pages folder) for higher level links (eg `/hats`)
than for lower level links (eg. `/hats/blue`).
I added a quick example of this. You can now go to `/hats` and the page used will be `hatList.js`
If you go to `/hats/blue` the page used will be `hat.js`
What is everybody's opinion on how it works? I added to option to make the `page` key in the …
> Routing rework

- pages/search.js
Updated state in an immutable way in the onChange handler for the checkboxes.
Only called `createSeachTypes` after the `setState` is complete
More info on why:
https://medium.freecodecamp.org/handling-state-in-react-four-immutable-approaches-to-consider-d1f5c00249d5
https://reactjs.org/docs/react-component.html#setstate
> fix(search.js): update state immutably

- lib/queries/facultyList.js
The original query was a 'whiteboard' build. $slug should have been the original search field.
mostly partial fix to issue #110
With the exception of one facultyDepartment, this fixes the multi-word slug issue. "Fine Arts" s the only one that removed the space entirely, instead of replacing it with a hyphen.
The following returns all of the department names and their slugs, showing that Fine Arts is the outsider.
````
{
facultyDepartments (first: 100) {
edges {
node {
name
slug
}
}
}
}
````
> fix(/lib/queries/facultyList.js): Changed search string to slug

- README.md
`npm dev` returns the help for npm because it isn't an acceptable command, however, `npm run dev` runs the npm script titled `dev`.
Thus I changed it in the README file.
> Fix npm command in README

- components/Hero.js
This is to fix [issue #134](https://github.com/fus-marcom/franciscan-react/issues/134). I have changed the following on the _Subtitle_ in `<Hero>`:
```css
margin-bottom: 0.35em;
```
to
```css
margin-bottom: 1.35em;
```
> Changed Hero subtitle marginBottom from 0.35em to 1.35em

- components/AppBar.js
* Added `title` attribute to the `<IconButton>` that wraps around `<MenuIcon />`.
* `title='Menu'`
* Added `<title>` element to the `<SvgIcon>` with class `classes.searchSVG`.
* `<title>Search Franciscan</title>`
> Add title attribute to Menu Button, add title element to searchSVG

- pages/search.js
I resolved the issue with the RegExp:    
<span className={classes.type}>
{**item.type.replace(/-|page/gi, ' ').trim()**}
</span>
> Issue#152: deletes '-' and 'page' from type in search
